name: Deploy Lambda

on:
  push:
    branches: [ "main" ]  # 例: mainブランチへのpushをトリガーにする

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      # 1. コードをチェックアウト
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. AWSクレデンシャルをセットアップ
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}   # or "ap-northeast-1" など

      # 3. zip が入っていない場合もあるのでインストール
      - name: Install zip
        run: sudo apt-get update && sudo apt-get install -y zip

      # 4. シェルスクリプトを実行
      - name: Deploy to Lambda
        run: |
          ./deploy.sh
