name: Deploy All Lambdas

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      # 1. コードをチェックアウト
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. AWSクレデンシャルをセットアップ
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. zip コマンド等が必要ならインストール (AWS CLIがデフォルトで入っている ubuntu-latest なら多分OK)
      - name: Install zip
        run: sudo apt-get update && sudo apt-get install -y zip

      # 4. `deploy.sh`をすべて探して実行
      - name: Deploy all
        run: |
          # すべてのdeploy.shを探し、各ファイルに対して:
          #   1) 実行権限を付与
          #   2) 実行
          for script in $(find . -name 'deploy.sh'); do
            echo "Found $script"
            chmod +x "$script"
            "$script"
          done
